FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY pnpm-lock.yaml package.json pnpm-workspace.yaml turbo.json ./


COPY apps/http-backend ./apps/http-backend
COPY packages ./packages


RUN pnpm install --frozen-lockfile


RUN pnpm run generate:db


RUN pnpm --filter http-backend build


EXPOSE 8080

CMD ["pnpm", "--filter", "http-backend", "start"]